/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_openscan_Capture */

#ifndef _Included_com_github_openscan_Capture
#define _Included_com_github_openscan_Capture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_openscan_Capture
 * Method:    createCapture
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_openscan_Capture_createCapture
  (JNIEnv *, jobject);

/*
 * Class:     com_github_openscan_Capture
 * Method:    destroyCapture
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_openscan_Capture_destroyCapture
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_openscan_Capture
 * Method:    setFrame
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_github_openscan_Capture_setFrame
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_github_openscan_Capture
 * Method:    runProcess
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_github_openscan_Capture_runProcess
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_github_openscan_Capture
 * Method:    setValue
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_github_openscan_Capture_setValue
  (JNIEnv *, jobject, jlong, jint, jdouble);

/*
 * Class:     com_github_openscan_Capture
 * Method:    getValue
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_github_openscan_Capture_getValue
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
