/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_openscan_Capture_Param */

#ifndef _Included_com_github_openscan_Capture_Param
#define _Included_com_github_openscan_Capture_Param
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
